originLat: 38.765852
originLon: -9.09281873
vehicle:
  control:
    SURGE_TO_RPM: 112
  safety_features:
    max_depth: 40.0 # [m]
    min_altitude: 1.0 # [m]
    min_altitude_ref: 1.5 # [m]
    wifi_timeout: 10.0 # [s]
    acoustic_timeout: 15.0 # [s]