processes:
    - name: 'simulation'
      launch_on_startup: true
      delay_before_start: 0.0
      cmd: 'roslaunch medusa_bringup sim.launch'
      args:
            - dynamics:= true
            - sensors:= true
      dependencies:
            []
    - name: 'bags'
      launch_on_startup: false
      delay_before_start: 0.0
      cmd: 'roslaunch medusa_bringup bags.launch'
      args:
            - prefix:= sim
            - onebag:= true
      dependencies:
            []
    - name: 'tfs'
      launch_on_startup: true
      delay_before_start: 0.0
      cmd: 'roslaunch medusa_bringup simulation_tfs.launch'
      args:
            - broadcast_tf:= true
      dependencies:
            []
    - name: 'addons'
      launch_on_startup: true
      delay_before_start: 0.0
      cmd: 'roslaunch medusa_bringup addons.launch'
      args:
            - console_path_parser:= true
            - console_server:= true
      dependencies:
            []
    - name: 'navigation'
      launch_on_startup: true
      delay_before_start: 4.0
      cmd: 'roslaunch medusa_bringup nav.launch'
      args:
            - filter:= true
            - gnss2utm:= true
            - auvstate2mstate:= true
            - usbl2pos:= true
      dependencies:
            []
    - name: 'controllers'
      launch_on_startup: true
      delay_before_start: 1.0
      cmd: 'roslaunch medusa_bringup controls.launch'
      args:
            - static_thruster_allocation:= true
            - inner_loops_pid:= true
            - waypoint:= true
            - path_following:= true
      dependencies:
            []
    - name: 'cooperative'
      launch_on_startup: true
      delay_before_start: 1.0
      cmd: 'roslaunch medusa_bringup cooperative.launch'
      args:
            - cpf_control:=true
            - cpf_wifi_receiver:=true
            - cpf_wifi_broadcaster:=true
      dependencies:
            []
    - name: 'acomms'
      launch_on_startup: false
      delay_before_start: 1.0
      cmd: 'roslaunch medusa_bringup comms.launch'
      args:
            - dmac:= false
            - data_serializer:= true
            - replier:= false
            - pinger:= true
            - pos2sim_modem:= true
            - dmac2medusa:= true
            - gnss2state:= true
      dependencies:
            []
    - name: 'planning'
      launch_on_startup: true
      delay_before_start: 5.0
      cmd: 'roslaunch medusa_bringup planning.launch'
      args:
            - dsor_paths:= true
      dependencies:
            []

