## --------------------------- ## 
#  medusa_addons                #
## --------------------------- ## 
#wifi_acoustic_safety:

#addons/rosbridge_server:

addons/console_path_parser:
    node_frequency: 5
    topics:
        subscribers: 
            Mission_String: /mblack/addons/Mission_String
            state: /mblack/nav/filter/state
            flag: /mblack/Flag
        publishers:
            Path_Section: /mblack/addons/path_section
            Formation: /mblack/addons/formation
            biased_formation: /mblack/addons/biased_formation
            WPRef: /mblack/addons/WPRef
            DepthRef: /mblack/ref/depth
            AltRef: /mblack/ref/altitude
            FullMission: /mblack/addons/full_mission
        services:
            reset_path: "/mblack/ResetPath"
            arc2d_path: "/mblack/SpawnArc2DPath"
            line_path: "/mblack/SpawnLinePath"
            pf_start: "/mblack/PFStart"
            pf_stop: "/mblack/PFStop"
            set_speed: "/mblack/SetConstVdVehicle"

addons/console_server:
    topics:
      services:
          wp_standard: "/mblack/controls/send_wp_standard"
          wp_loose: "/mblack/controls/send_wp_loose"
          wp_heading: "/mblack/controls/send_wp_heading"
      console:
          waypoint: "wp_standard"
    
addons/aggregator:
    pub_rate: 2.0

## --------------------------- ## 
#  medusa_sim                   #
## --------------------------- ## 
## dynamic model
sim/dsor_sim:
    frame_id: "mblack"
    node_frequency: 100 # (Hz)
    topics:
        subscribers:
            thrusters: "/mblack/thrusters/rpm_command"
        publishers:
            odometry: "/mblack/sim/dynamics/position"
        services:
            start_pause: "/mblack/sim/pause_start"

## sensor simulator
sim/sensors:
    node_frequency: 10
    # topics
    #   subscribers: [ (std::vector<std::strings>) Subscriber: vehicle state in nav_msgs::Odometry, thruster output from innerloops in medusa_msgs::Thruster]
    #   publishers : [ (std::vector<std::strings>) Publishers: sensors (position, velocity, orientation, gnss, range), model, thrusters (value and status)
    topics:
        subscribers: [ "/mblack/sim/dynamics/position"]
        publishers : [
            "/mblack/measurement/position",
            "/mblack/measurement/velocity",
            "/mblack/measurement/orientation",
            "/mblack/sensors/gnss",
            "/mblack/sensors/range",
            "/mblack/sim/model/state",
            "/mblack/diagnostics/thrusterStatus"
        ]    
    services:
      enable_dvl: "/mblack/sim/enable_dvl"
      enable_altimeter: "/mblack/sim/enable_altimeter"

## --------------------------- ## 
#  medusa_nav                   #
## --------------------------- ## 
### Sensor mblack for the frame "odom"
nav/filter:
    node_frequency: 10      # ROS node rate
    topics:
        subscribers: [       # reset, position topic, velocity topic and orientation and acceleration (optional) topic
            "/mblack/nav/reset", "/mblack/measurement/position", "/mblack/measurement/velocity", "/mblack/measurement/orientation"
        ]
        publishers: [        # state topic, debug topic
            "/mblack/nav/filter/state", "/mblack/nav/filter/debug"
        ]
        currents: "/mblack/nav/filter/currents"
    topics_dr:
       velocity: "/mblack/measurement/velocity"
       orientation: "/mblack/measurement/orientation"
       true_state: "/mblack/nav/filter/state"
       flag: "/mblack/Flag"
       dead_reckoning: "/mblack/nav/filter/state_dr"
       dead_reckoning_console: "/mblack/State_dr"
    services_dr:
       reset_filter_dr: "/mblack/nav/reset_filter_dr"
        
### Converting sensor_msgs::NavSatFix to medusa_msgs::Measurement data type
nav/gnss2utm:
    node_frequency: 10
    topics:
        subscribers: [ "/mblack/sensors/gnss" ]
        publishers: [ "/mblack/measurement/position" ]
        ground_truth: "/mblack/State_gt"
    services:
        enable_gps: "/mblack/sensor/enable_gps"

nav/usbl2pos:
    node_frequency: 10
    topics:
        subscribers: [
            "/mblack/sensors/usbl_fix", "/mblack/acomms/nav/filter/state", "/mblack/nav/filter/state"
        ]
        publishers: [ "/mblack/measurement/position", "/mblack/State_usbl_est", "/mblack/nav/filter/usbl_est" ]

nav/range2pos:
    node_frequency: 10
    t_sync: 2
    topics:
        subscribers: [ "/mblack/sensors/range", "/mblack/nav/filter/state" ]
        publishers: [ "/mblack/measurement/position" ]

nav/auvstate2mstate:
    node_frequency: 10
    topics:
        subscribers: [ "/mblack/nav/filter/state", "/mblack/drivers/inside_pressure/data", "/mblack/sensors/gnss" ]
        publishers:  [ "/mblack/State" ]

## --------------------------- ## 
#  medusa_control               #
## --------------------------- ## 
### Inner Loops
controls/inner_loops:
    node_frequency: 10.0 # Time parameters
    topics:
        subscribers:
            state: "/mblack/nav/filter/state"
            surge: "/mblack/ref/surge"
            yaw: "/mblack/ref/yaw"
            yaw_rate: "/mblack/ref/yaw_rate"
            depth: "/mblack/ref/depth"
            altitude_ref: "/mblack/ref/altitude"
            altitude: "/mblack/controls/Altitude"
            altimeter: "/mblack/controls/Altimeter"
        publishers:
            thrusters: "/mblack/thrusters/rpm_command"
            thrusters_model: "/mblack/thrusters/model"

controls/inner_loops_forces:
    # ROS node rate 
    node_frequency: 10.0 # Time parameters
    # ROS Topics
    topics:
        subscribers:
            yaw: "/mblack/ref/yaw"
            pitch: "/mblack/ref/pitch"
            roll: "/mblack/ref/roll"
            yaw_rate: "/mblack/ref/yaw_rate"
            pich_rate: "/mblack/ref/pitch_rate"
            roll_rate: "/mblack/ref/roll_rate"
            surge: "/mblack/ref/surge"
            sway: "/mblack/ref/sway"
            heave: "/mblack/ref/heave"
            depth: "/mblack/ref/depth"
            altitude: "/mblack/ref/altitude"
            altitude_safety: "/mblack/ref/altitude_safety"
            depth_safety: "/mblack/ref/depth_safety"
            state: "/mblack/nav/filter/state"
        publishers:
            thrust_body_request: "/mblack/thrust_body_request"
            thrusters: "/mblack/thrusters/rpm_command"

### Way Point
controls/waypoint:
    node_frequency: 10.0
    topics:
        publishers:
            yaw_ref: "/mblack/ref/yaw"
            yaw_rate_ref: "/mblack/ref/yaw_rate"
            u_ref: "/mblack/ref/surge"
            v_ref: "/mblack/ref/sway"
            flag: "/mblack/Flag"
        subscribers:
            flag: "/mblack/Flag"
            state: "/mblack/nav/filter/state"
        services:
            wp_standard: "/mblack/controls/send_wp_standard"
            wp_loose: "/mblack/controls/send_wp_loose"
            wp_heading: "/mblack/controls/send_wp_heading"


### Path Following
controls/path_following:
    node_frequency: 10.0
    flag: "/mblack/Flag"
    topics:
        subscribers:
            state: "/mblack/nav/filter/state"
            path: "/mblack/PathData"
            vc: "/mblack/PF/vc"
        publishers:
            # Publishers for linear motion
            surge: "/mblack/ref/surge"
            sway: "/mblack/ref/sway"
            heave: "/mblack/ref/heave"
    
            # Publishers for angular motion
            roll: "/mblack/ref/roll"
            roll_rate: "/mblack/ref/roll_rate"
            pitch: "/mblack/ref/pitch"
            pitch_rate: "/mblack/ref/pitch_rate"
            yaw: "/mblack/ref/yaw"
            yaw_rate: "/mblack/ref/yaw_rate"
    
            # Publishers for the virtual target
            rabbit: "/mblack/Gamma"

            # Observer for the currents
            observer:
                x: "/mblack/current/x"
                y: "/mblack/current/y"
            
            # Publish info for plots
            pfollowing_debug: "/mblack/pfollowing/debug"

        # Define here the service names to switch between controllers 
        services:
            # Service names to start and stop the path following algorithm
            start_pf: "/mblack/PFStart"
            stop_pf: "/mblack/PFStop"
            updates_gains_pf: "/mblack/PFUpdateGains"
            reset_vt_pf: "/mblack/ResetVT"
    
            # Service names to switch the path following algorithm
            marcelo_pf: "/mblack/PFSetMarcelo"
            aguiar_pf: "/mblack/PFSetAguiar"
            brevik_pf: "/mblack/PFSetBrevik"
            fossen_pf: "/mblack/PFSetFossen"
            romulo_pf: "/mblack/PFSetRomulo"
            lapierre_pf: "/mblack/PFSetLapierre"
            pramod_pf: "/mblack/PFSetPramod"
            samson_pf: "/mblack/PFSetSamson"
            # Service names related to the path
            reset_path: "/mblack/ResetPath"
            set_path_mode: "/mblack/SetMode"
            # Service names related to the waypoint
            wp_standard: "/mblack/controls/send_wp_standard"
   
### Cooperative control law
controls/cpf_control:
    node_frequency: 10
    topics:
        publishers: 
            vc: "/mblack/PF/vc"
            cpf_server_input: "/mblack/Internal/Gamma"
        subscribers:
            internal_gamma: "/mblack/PathData"
            external_gamma: "/mblack/External/Gamma"
        services:
        # Service names to start and stop the path following algorithm
            start_cpf: "/mblack/CPFStart"
            stop_cpf: "/mblack/CPFStop"
            change_topology: "/mblack/CPFChangeTopology"

## --------------------------- ## 
#  medusa_planning              #
## --------------------------- ##
planning/dsor_paths:
    node_frequency: 10.0
    frame_id: "Path_frame"
    topics:
        subscribers:
            gamma: "/mblack/Gamma"
            vehicle_state: "/mblack/nav/filter/state"
        publishers:
            path_data: "/mblack/PathData"
            virtual_target_state: "/mblack/Virtual/State"
        # Services for constructing a path
        services:
            reset_path: "/mblack/ResetPath"
            set_mode: "/mblack/SetMode"
            arc2d_path: "/mblack/SpawnArc2DPath"
            bernoulli_path: "/mblack/SpawnBernoulliPath"
            circle2d_path: "/mblack/SpawnCircle2DPath"
            line_path: "/mblack/SpawnLinePath"
            speed:
                const_rabbit_speed: "/mblack/SetConstVdRabbit"
                const_vehicle_speed: "/mblack/SetConstVdVehicle"

## --------------------------- ## 
#  medusa_comms                #
## --------------------------- ## 
#acomms/modem:

acomms/pinger:
    topics:
        publishers:
            modem_send: "/mblack/acomms/modem/send"
            meas_usbl_fix: "/mblack/sensors/usbl_fix"
            trigger_serialization: "/mblack/acomms/scheme/trigger_serialization"
            deserialize: "/mblack/acomms/scheme/payload_to_deserialize"
        subscribers:
            enable: "/mblack/acomms/scheme/enable"
            modem_recv: "/mblack/acomms/modem/recv"
            payload: "/mblack/acomms/serializer/payload_to_transmit"

acomms/replier:
    topics:
        publishers:
            modem_send: "/mblack/acomms/modem/send"
            meas_usbl_fix: "/mblack/sensors/usbl_fix"
            trigger_serialization: "/mblack/acomms/scheme/trigger_serialization"
            deserialize: "/mblack/acomms/scheme/payload_to_deserialize"
        subscribers:
            modem_recv: "/mblack/acomms/modem/recv"
            serialize: "/mblack/acomms/serializer/payload_to_transmit"

acomms/data_serializer:
    topics:
        publishers:
            to_modem: "/mblack/acomms/serializer/payload_to_transmit"
        subscribers:
            from_modem: "/mblack/acomms/scheme/payload_to_deserialize"
            trigger: "/mblack/acomms/scheme/trigger_serialization"
        
acomms/dmac2medusa:
    topics:
        publishers:
            medusa_fix: "/mblack/sensors/usbl_fix"
        subscribers:
            dmac_fix: "/mblack/acomms/modem/measurement/usbl_fix"

acomms/gnss2state:
    topics:
        subscribers: [
            "/mblack/acomms/nav/filter/gnss"
        ]
        publishers: [
            "/mblack/acomms/nav/filter/state",
            "/mblack/state/utmzone"
        ]

acomms/pos2sim_modem:
    topics/subscribers/position: "/mblack/sim/dynamics/position"

acomms/cpf_gamma_server:
    node_frequency: 10
    topics:
      subscribers:
        internal_gamma: "/mblack/Internal/Gamma"
      publishers:
        cpf_gamma: "/mblack/External/Gamma"
        
acomms/cpf_gamma_client:
    node_frequency: 10
    topics:
      subscribers:
        internal_gamma: "/mblack/Internal/Gamma"
      publishers:
        cpf_gamma: "/mblack/External/Gamma"


    
